DevCard/DevCard_Project/Models/Contact.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace DevCard_Project.Models
{
    public class Contact
    {
        [MinLength(2, ErrorMessage = "حداقل تعداد کاراکتر نام، 2 تا می باشد.")]
        [MaxLength(10, ErrorMessage = "حداکثر تعداد کاراکتر نام، 10 تا می باشد.")]
        [Required(ErrorMessage ="اجباریه")]
        public string Name { get; set; }

        [EmailAddress(ErrorMessage = "مقدار وارد شده ایمیل صحیح نیست")]
        [Required(ErrorMessage = " اینم اجباریه")]
        public string Email { get; set; }

        public int? Service { get; set; }

        [Required(ErrorMessage = "حالا یه چارتا کلمه بنویسی، چی میشه؟!")]
        public string Message { get; set; }
        
        [ValidateNever]
        public SelectList? Services { get; set; }
    }
}

DevCard/DevCard_Project/Controllers/HomeController.cs
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Mime;
using DevCard_Project.Data;
using DevCard_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DevCard_Project.Controllers
{
    //[Route("/teste/contacte/{action}")]
    //[Route("/teste/contacte")]
    public class HomeController : Controller
    {
        private readonly List<Service> _selectList = new List<Service>
        {
            new Service(1, "Gold"),
            new Service(2, "Silver"),
            new Service(3, "Platin"),
            new Service(4, "nul")
        };
        //[Route("MyIndex")]
        public IActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        [HttpGet("ContactPage")]
        //[Route("ContactPage/{esm}/{type}/{salsakht}")]
        public IActionResult Contact(string esm, string type, int salsakht)
        {
            var model = new Contact
            {
               Services = new SelectList(_selectList, "Id", "Name")
            };

            //var model = new Contact();
            return View(model);
        }

        //[HttpPost]
        //public FileResult Contact(IFormCollection form)
        //{
        //    var a = form.TryGetValue("name", out var name);
        //    var b = form.TryGetValue("email", out var email);
        //    var c = form.TryGetValue("service", out var service);
        //    var d = form.TryGetValue("message", out var message);

        //    var fileByte = System.IO.File.ReadAllText("wwwroot/json.txt");
        //    fileByte = fileByte.Replace("{name}", name).Replace("{email}", email).Replace("{service}", service).Replace("{message}", message);

        //    var fileName = "Result.txt";
        //    var bytes = System.Text.Encoding.UTF8.GetBytes(fileByte);

        //    return File(bytes, MediaTypeNames.Text.RichText, fileName);
        //}

        [HttpPost]
        public IActionResult Contact(Contact model)
        {
            model.Services = new SelectList(_selectList, "Id", "Name", _selectList.FirstOrDefault(x=> x.Id == model.Service).Name);

            if (!ModelState.IsValid)
            {
                ViewBag.Error = "خطا داری، برو درستش کن بیا!";
                return View(model);
            }

            ModelState.Clear();
            model = new Contact
            {
                Services = new SelectList(_selectList, "Id", "Name")
            };
            ViewBag.Success = "آفرین، درسته...";
            return View(model);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        public IActionResult ProjectDetails(int id)
        {
            var model = ProjectDetail.GetProjectBy(id);
            return View(model);
        }
    }
}

DevCard/DevCard_Project/Controllers/TestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Mime;
using System.Xml.Linq;

namespace DevCard_Project.Controllers
{
    public class TestController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        //public ViewResult Index()
        //{
        //    return View("Asli");
        //}

        //public PartialViewResult Index()
        //{
        //    return PartialView("Header");
        //}

        //public FileResult Index()
        //{
        //    var fileByte = System.IO.File.ReadAllBytes("wwwroot/me.png");
        //    var filename = "TestFile.png";
        //    return File(fileByte, MediaTypeNames.Image.Jpeg, filename);
        //}

        //public ContentResult Index()
        //{
        //    return Content("<h1>Hi Everyone, Nice To Meet You", "Text/html");
        //}

        //public EmptyResult Index() 
        //{
        //    return new EmptyResult();   
        //}

        //public JsonResult Index()
        //{
        //    return Json(new
        //    {
        //        id = 1,
        //        name = "Ali",
        //        family = "azami",
        //        age = 28,
        //        job = "Developer"
        //    });

        //}

        //public JavaScriptResult Index()
        //{
        //    return new JavaScriptResult("alert('Salam Salam, Zendegi Salam!!!')");
        //}

        //public class JavaScriptResult : ContentResult
        //{
        //    public JavaScriptResult(string content)
        //    {
        //        Content = content;
        //        ContentType = "application/javascript";
        //    }

        //}

        //public RedirectResult Index()
        //{
        //    return Redirect("https://www.daneshrefah.ir");
        //}

        //public RedirectToActionResult Index()
        //{
        //    return RedirectToAction("Contact","Home");
        //}

        public IActionResult Index()
        { 
        //return new OkResult();
        //return new UnauthorizedResult();
        //return new BadRequestResult();
        //return new NoContentResult();
        return new NotFoundResult();
        }
    }
}

DevCard/DevCard_Project/ViewComponents/ArticlesViewComponent.cs
using DevCard_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_Project.ViewComponents
{
    public class ArticlesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var articles = new List<Article>()
            {
                new Article(1, "موبایل بانک" ,new List<string>{ "مدیریت حساب های مشتری", "مدیریت کارت های مشتری", "مدیریت تسهیلات و تعهدات", "انتقال وجه هوشمند", "کارت به کارت" } , "mobilebank.jpg","https://www.daneshrefah.ir/UI/Products#MobileBank"),
                new Article(2, "اینترنت بانک" ,new List<string>{ "مدیریت حساب های مشتری", "مدیریت کارت های مشتری", "مدیریت تسهیلات و تعهدات", "کارتابل خدمات اشتراکی", "مدیریت حساب های شرکتی" }, "internetbank.jpg","https://www.daneshrefah.ir/UI/Products#InternetBank"),
                new Article(3, "مدیریت کانال" ,new List<string>{ "مدیریت کانال های ارتباطی", "مدیریت کاربران کانال ها", "امکان تعریف سقف به ازاء کانال", "امکان مدیریت فرآیندهای کسب و کار", "امکان کارتابل فرآیندی" }, "wwrofhyyt0nw.jpeg","https://www.daneshrefah.ir/UI/Products#ChannelManagement"),
                new Article(4, "Core Bank" ,new List<string>{ "حساب‌ها و سپرده‌ها", "پرداخت و نقل‌وانتقال مالی", "کارت‌های بانکی", "مدیریت مشتریان (CIF)", "گزارش‌گیری و تحلیل داده" }, "logo.png","https://www.daneshrefah.ir/UI/Products#CoreBank"),
                new Article(5, "پیام رسان" ,new List<string>{ "ثبت‌نام و احراز هویت: ایمیل، شماره موبایل، یا شبکه‌های اجتماعی", "چت فردی و گروهی: ارسال پیام متنی، صوتی و تصویری",
                   "تماس صوتی و تصویری: کیفیت بالا و رمزنگاری‌شده", "اشتراک‌گذاری فایل: پشتیبانی از انواع فایل‌ها (تصویر، ویدئو، اسناد)", "مزنگاری پیام‌ها: امنیت سرتاسری (E2EE)" }, "ac93fc65a2d2272c0f8991b77af721d6.jpg","https://www.daneshrefah.ir/UI/Products#Messenger"),
                new Article(6, "Super App" ,new List<string>{ "سرویس‌های کارت مانند کارت به کارت (از مبدا کلیه بانک‌ها )، موجودی، سه گردش", "سرویس‌های استعلام قبوض",
                   "پرداخت حق بیمه تامین اجتماعی", "سرویس‌های خرید شارژ و بسته اینترنتی", "سرویس‌های چک صیادی مانند ثبت و استعلام" }, "202406141718347363621233.png","https://www.daneshrefah.ir/UI/Products#SuperApp"),
                new Article(7, "کیف پول (Wallet)" ,new List<string>{ "نرم‌افزار کیف پول الکترونیکی (E-Wallet) امکانات زیر را برای پاسخگویی به نیازهای کاربران در انجام تراکنش‌های مالی دیجیتال فراهم می کند"}, "What-Do-You-Mean-By-A-Digital-Wallet.jpg","https://www.daneshrefah.ir/UI/Products#Wallet"),
                new Article(8, "سوئیچ PSP" ,new List<string>{ "ماژول مدیریت تراکنش (Transaction Management)", "ماژول مسیریابی (Routing)",
                   "ماژول امنیت (Security)", "ماژول نظارت و گزارش‌گیری (Monitoring and Reporting)", "ماژول مدیریت کارت (Card Management)" }, "nn1xys0m_thumb3.jpg", "https://www.daneshrefah.ir/UI/Products#PspSwitch"),
                new Article(9, "پلتفرم معتمد مالیاتی (TSP)" ,new List<string>{ "سوئیچ TSP", "ثبت و مدیریت صورتحساب‌ها (Invoice Management)",
                   "اعتبارسنجی و تایید اطلاعات (Validation and Verification)", "ارسال به سامانه مودیان (Invoice Submission)", "گزارش‌گیری و تحلیل داده‌ها (Reporting and Analytics)" }, "لوگو_های-عصر-تراکنش-83-1.jpg", "https://www.daneshrefah.ir/UI/Products#TspSwitch"),
                new Article(10, "چکسام (Cheqsum)" ,new List<string>{ "سامانه چکسام با بهره‌گیری از تکنولوژی‌های مدرن و نوآوری‌هایی که در آن استفاده می‌شود، " +
                "به مشتریان حقوقی امکان می‌دهد فرآیند ثبت و مدیریت چک را بصورت غیرحضوری و گروهی بهبود بخشند و زمان و هزینه مورد نیاز را به شدت کاهش دهند." +
                " این سامانه با ایجاد یک رابط کاربری آسان و قابل دسترس بصورت آنلاین، به مشتریان امکان می‌دهد اطلاعات مربوط به چک‌های خود را به راحتی و با کیفیت بالا ثبت و پیگیری کنند."}, "Checksum.svg.png","https://www.daneshrefah.ir/UI/Products#Cheqsum"),
                new Article(11, "DB2 on REST (Z Service)" ,new List<string>{ "اجرای فرمان‌های دیتابیس مانند Query و Stored Procedure از طریق ساختاری یکپارچه به صورت Rest، و فارغ از زبان برنامه نویسی، آرزوی دیرینه‌ی تمام برنامه‌نویسان است." +
                " این پروژه، به صورت پویا، تمامی پراسیجرهایی که قابلیت اجرا داشته باشند را از جداول مورد نیاز دیتابیس Db2(z/os,LUW) با استفاده از ابزارهای طراحی شده توسط این شرکت، بارگذاری کرده " +
                "و در حافظه Cache به جهت دسترسی با سرعت بالا و عدم بارگذاری مجدد ساختار پراسیجرها نگهداری می‌کند." +
                " از مزیت‌های مهم این پروژه می‌توان به امکان دسترسی‌های موردی به سرویس‌های دیتابیس از طریق SSO، قابلیت لاگ به ازای هر درخواست ورودی و پاسخ خروجی از دیتابیس بصورت غیرهمزمان (Async) " +
                "به چندین مرکز لاگ (ELK، MongoDb و ...) و قابلیت مهم HA(Horizontal AutoScaling) و مدیریت درخواست‌های بالا (LoadBalance) اشاره کرد"}, "1_24061261_129965491,640x360,b,1_3.jpg", "https://www.daneshrefah.ir/UI/Products#ZService"),
                new Article(12, "خدمات مشاوره" ,new List<string>{ "ارزیابی و تحلیل فرآیندهای سازمان", "طراحی معماری سازمانی", "طراحی و پیاده سازی زیر ساخت DevOps", "طراحی اپلیکیشن های موبایلی در حوزه پرداخت", "راه حل های مدرن در حوزه معماری Core Bank" }, "thumb879293770.jpg", "https://www.daneshrefah.ir/UI/Products#Consultation"),

            };
            return View("_articles", articles);
        }
    }
}

DevCard/DevCard_Project/ViewComponents/ProjectsViewComponent.cs
using DevCard_Project.Data;
using DevCard_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace DevCard_Project.ViewComponents
{
    public class ProjectsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var projects = ProjectDetail.GetProjects();

            return View("_projects", projects);
        }
    }
}

DevCard/DevCard_Project/Views/Home/Contact.cshtml
@model Contact
@{
    ViewData["Title"] = "ارتباط با ما";
    // ViewData["Error"]
    // ViewData["Success"]
}


<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
        <h2 class="heading">ارتباط با ما</h2>
        <div class="intro">
            <p>
                شما می توانید از طریق فرم زیر با ما ارتباط بگیرید. لطفا پس از پرکردن آیتم ها، پیغام مورد نظر را
                نوشته و ارسال کنید.
            </p>
            <p>از طریق شبکه های اجتماعی با ما در ارتباط باشید</p>
            <ul class="list-inline mb-0">
                <li class="list-inline-item mb-3">
                    <a class="twitter" href="#">
                        <i class="fab fa-twitter fa-fw fa-lg"></i>
                    </a>
                </li>

                <li class="list-inline-item mb-3">
                    <a class="linkedin" href="#">
                        <i class="fab fa-linkedin-in fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="github" href="#">
                        <i class="fab fa-github-alt fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item">
                    <a class="instagram" href="#">
                        <i class="fab fa-instagram fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="stack-overflow" href="#">
                        <i class="fab fa-stack-overflow fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="medium" href="#">
                        <i class="fab fa-medium-m fa-fw fa-lg"></i>
                    </a>
                </li>
                <li class="list-inline-item mb-3">
                    <a class="codepen" href="#">
                        <i class="fab fa-codepen fa-fw fa-lg"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        <form id="contact-form" class="contact-form col-lg-8 mx-lg-auto" method="post" asp-action="Contact" asp-controller="Home">
            @if (!string.IsNullOrWhiteSpace(ViewBag.Success))
            {
                <p class="alert-success p-2">@ViewBag.Success</p>
            }
            @if (!string.IsNullOrWhiteSpace(ViewBag.Error))
            {
                <p class="alert-danger p-2">@ViewBag.Error</p>
            }
            <h3 class="text-center mb-3">در دسترس باشید!</h3>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Name">نام</label>
                    <input type="text" class="form-control" asp-for="Name" placeholder="نام">
                    <span class="text-danger" asp-validation-for="Name"></span>

                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only" asp-for="Email">ایمیل</label>
                    <input type="email" class="form-control" asp-for="Email" placeholder="ایمیل">
                    <span class="text-danger" asp-validation-for="Email"></span>

                </div>
                <div class="form-group col-12">
                    <select class="custom-select" asp-for="Service" asp-items="Model.Services">
                        <option value="0" selected="selected">سرویس مورد نظر خود را انتخاب کنید...</option>
                    </select>
                    <span class="text-danger" asp-validation-for="Services"></span>


                </div>
                <div class="form-group col-12">
                    <label class="sr-only" for="cmessage">پیغام شما</label>
                    <textarea class="form-control" asp-for="Message"
                              placeholder="پیغام خود را وارد نمایید ..." rows="10"></textarea>
                    <span class="text-success" asp-validation-for="Message"></span>

                </div>
                <div class="form-group col-12">
                    <button type="submit" class="btn btn-block btn-primary py-2">ارسال</button>
                </div>
            </div>
        </form>
    </div>
</section>


@* <script src="@Url.Action("Index", "Test")" type="text/javascript"></script>
 *@

DevCard/DevCard_Project/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "صفحه اصلی";
}

<section class="about-me-section p-3 p-lg-5 theme-bg-light">
	<div class="container">
		<div class="profile-teaser media flex-column flex-lg-row">
			<img class="profile-image mb-3 mb-lg-0 ml-lg-5 mr-md-0" src="~/assets/images/me.png" alt="">
			<div class="media-body">
				<h2 class="name font-weight-bold mb-1">علی اعظمی</h2>
				<div class="tagline mb-3">Junior Developer</div>
				<div class="bio mb-4">
					<a>
						شرکت دانش رفاه پردیس، یکی از شرکت های تابعه بانک رفاه کارگران می باشد که از سال 1400 استارت شروع به کار خود را زده است.
						ساختمان شرکت واقع در خ طالقانی تقاطع وصال شیرازی پ 568 بوده و رئیس شرکت جناب آقای مهندس پرهام محمدی می باشد.
					</a>
				</div>
				<div class="mb-4">
					<a class="btn btn-primary mr-2 mb-3" href="https://www.daneshrefah.ir">
						<i class="fas fa-arrow-alt-circle-right ml-2"></i><span class="d-none d-md-inline">
							برو به دانش رفاه
						</span> 
					</a>
					<a class="btn btn-secondary mb-3" href="https://sanjesh.org">
						<i class="fas fa-file-alt ml-2"></i>
						<span class="d-none d-md-inline">مشاهده </span> نمونه کارها
					</a>
				</div>
			</div>

		</div>
	</div>
</section>

@* <partial name="Projects"/> *@

@await Component.InvokeAsync("Projects")

<div class="container">
	<hr>
</div>

@await Component.InvokeAsync("Articles")

DevCard/DevCard_Project/Views/Home/ProjectDetails.cshtml
@model Project

@{
    ViewData["Title"] = "جزئیات محصولات";
}

<section class="cta-section theme-bg-light py-5">
    <div class="container text-center single-col-max-width">
    </div>
</section>
<section class="contact-section px-3 py-5 p-md-5">
    <div class="container">
        <table class="table-bordered alert-primary table-hover">
            <thead>
                <tr class="text-center">
                    <td>شناسه</td>
                    <td>تصویر</td>
                    <td>اسم محصول</td>
                    <td>توضیحات</td>
                    <td>کاربر</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.Id</td>
                    <td><img src="~/assets/images/@Model.Image" width="100px"></td>
                    <td>@Model.Name</td>
                    <td>@Model.Description</td>
                    <td>@Model.Client</td>
                </tr>
            </tbody>
        </table>
    </div>
</section>